### ISSUE TITLE
Device properties -Serial number field

### ISSUE THREAD

**Issue by Faq** [Gurux/GXDLMSDirector#1]
Serial number field deletes 0 in start of number. For example Elgama uses 0 in start of meter numbers for all Gama meters with DLMS.

Director Version: 7.0.21.1

**Comment by Faq** [comment]
Passed more than a year and noone was able to resolve this?

**Comment by gurux01** [comment]
Hi,

Standars says that serial number is counted using this formula.
NS % 10000 + 1000
SL7000 is little bit problem because manufacture do not exists any more and it is old meter.
There are some other problems with the meter.

Problem is that there is no one to ask and we are not even sure is SL 7000 supporting Serial number server addressing.

BR,

Mikko

**Comment by Faq** [comment]
No point to argue, after half year constantly asking you in mail to connect to exact same meters connected to the grid.
